version: 2
updates:
  - package-ecosystem: npm
    directory: "/dashboard"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
