version: '3'

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_USER=mailbadger
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=mailbadger
    volumes:
      - dbdata:/var/lib/mysql

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
  app:
    image: news-maily/app
    command: /app
    ports:
      - "8080:8080"
    volumes:
      - ./maily.db:/maily.db
    depends_on:
      - mysql
      - nsqd
    environment:
      # - ENVIRONMENT=prod
      - DATABASE_DRIVER=mysql
      - MYSQL_HOST=mysql
      - MYSQL_USER=mailbadger
      - MYSQL_PASS=changeme
      - MYSQL_DATABASE=mailbadger
      - PORT=8080
      - SKIP_TLS=true
      - LOG_LEVEL=info
      - DOMAIN_URL=http://localhost:8080
      - AUTH_SECRET=changeme
      - EMAILS_TOKEN_SECRET=changeme
      - SESSION_AUTH_KEY=secret
      - SESSION_ENCRYPT_KEY=LkcjY97j2yY3jQFUTf1viABjY1Ict3gJ
      - SYSTEM_EMAIL_SOURCE=noreply@example.com
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
      # - ENABLE_SIGNUP=true
      # - RECAPTCHA_SECRET=abcdef
      - NSQD_HOST=nsqd
      - NSQD_PORT=4150
  bulksender:
    image: news-maily/app
    command: /consumers/bulksender
    volumes:
      - ./maily.db:/maily.db
    depends_on:
      - app
    environment:
      - DATABASE_DRIVER=mysql
      - MYSQL_HOST=mysql
      - MYSQL_USER=mailbadger
      - MYSQL_PASS=changeme
      - MYSQL_DATABASE=mailbadger
      - NSQLOOKUPD_HOST=nsqlookupd
      - NSQLOOKUPD_PORT=4161
      - LOG_LEVEL=info
  campaigner:
    image: news-maily/app
    command: /consumers/campaigner
    volumes:
      - ./maily.db:/maily.db
    depends_on:
      - app
    environment:
      - DATABASE_DRIVER=mysql
      - MYSQL_HOST=mysql
      - MYSQL_USER=mailbadger
      - MYSQL_PASS=changeme
      - MYSQL_DATABASE=mailbadger
      - NSQLOOKUPD_HOST=nsqlookupd
      - NSQLOOKUPD_PORT=4161
      - NSQD_HOST=nsqd
      - NSQD_PORT=4150
      - LOG_LEVEL=info

volumes:
  dbdata: