version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
  app:
    image: news-maily/app
    command: /app
    ports:
      - "8080:8080"
    volumes:
      - ./maily.db:/maily.db
    depends_on:
      - nsqd
    environment:
      - DATABASE_DRIVER=sqlite3
      - DATABASE_CONFIG=maily.db
      - PORT=8080
      - NSQD_HOST=nsqd
      - NSQD_PORT=4150
      - SKIP_TLS=true
      - LOG_LEVEL=info
      - DOMAIN_URL=https://example.com
      - AUTH_SECRET=changeme #secret for signing JWTs
      # - ENABLE_SIGNUP=true
      # - RECAPTCHA_SECRET=abcdef
  bulksender:
    image: news-maily/app
    command: /consumers/bulksender
    volumes:
      - ./maily.db:/maily.db
    depends_on:
      - app
    environment:
      - DATABASE_DRIVER=sqlite3
      - DATABASE_CONFIG=maily.db
      - NSQLOOKUPD_HOST=nsqlookupd
      - NSQLOOKUPD_PORT=4161
      - LOG_LEVEL=info
  campaigner:
    image: news-maily/app
    command: /consumers/campaigner
    volumes:
      - ./maily.db:/maily.db
    depends_on:
      - app
    environment:
      - DATABASE_DRIVER=sqlite3
      - DATABASE_CONFIG=maily.db
      - NSQLOOKUPD_HOST=nsqlookupd
      - NSQLOOKUPD_PORT=4161
      - NSQD_HOST=nsqd
      - NSQD_PORT=4150
      - LOG_LEVEL=info